### ISSUE TITLE
スレッドのメッセージリンク読み上げ処理に対応

### ISSUE THREAD

**Issue by book000** [jaoafa/JDA-VCSpeaker#127]
### 対象の機能

メッセージ読み上げ

### 強化・改善の内容

`https://discord.com/channels/597378876556967936/924324540631367761/925439477076357120` のようなメッセージリンクに対応する

**Comment by book000** [comment]
JDA v5系へのアップデート必須

**Comment by yuuahp** [comment]
#vc 内のスレッドのみ？

**Comment by book000** [comment]
> メッセージリンクの読み上げ

なので、読み上げるチャンネルの話ではないです
vcチャットチャンネルにメッセージリンクが張られた場合の挙動

**Comment by yuuahp** [comment]
ごめんURLのことを言いたかった

**Comment by yuuahp** [comment]
リンク先がプライベートチャンネルとかスレッドとかだったらまずいんじゃないかと思ったんだけど

**Comment by book000** [comment]
現行のメッセージリンクでもチャンネル名と投稿者名拾って読み上げているので、まあ大丈夫なんじゃないかなあと想定
そもそもそんなあぶなっかしいところのメッセージのリンクを貼るなって話ではあるので…

**Comment by yuuahp** [comment]
たしかに...

**Comment by book000** [comment]
あえて懸念するならJDAをv5系にアプデしていいものなのかが微妙かなあ…

**Comment by yuuahp** [comment]
使ってたのが非推奨になるとかそういう？

**Comment by book000** [comment]
まあそう

https://github.com/DV8FromTheWorld/JDA/releases/tag/v5.0.0-alpha.1 を見る限り、Removedなものはかなり多いしJavajaotan2でv5系に上げた時も[ちょっと修正](https://github.com/jaoafa/Javajaotan2/commit/2e692243991023012effeca0014a5036f64d8acc)する必要はあったのよね
それ自体は別に大した手間じゃないにしても、v5自体はベータだから不安定な点をどう考えるかは難しい…

**Comment by yuuahp** [comment]
v5テストで結構な時間動かしてるけど安定してる気がする
Removedは書き換えなきゃいけないけど

**Comment by book000** [comment]
んじゃあまあv5に上げるか～
