### ISSUE TITLE
URLの省略を最後まで行って欲しい

### ISSUE THREAD

**Issue by X8Z-p0keR** [jaoafa/JDA-VCSpeaker#25]
特にdiscordなどのリンクを最後の数字だけ読み上げる、というようなことがあるのでURLを最後まで省略して欲しい

**Comment by yuuahp** [comment]
例えば
`https://discord.com/xxxxx/yyyyy/zzzzz`
だとどこを読み上げればいいですか？

**Comment by poker99981** [comment]
URLは全部読み上げなしor「URL省略(と読み上げ)」でも個人的には支障はないかなと思います。

**Comment by yuuahp** [comment]
それだと #9 と競合すると思います
「URL省略-zzzzz」でも大丈夫ですか？
@book000 も意見お願いしたいです

**Comment by yuuahp** [comment]
あと、Discordのメッセージリンクの場合
「メッセージリンク-`リンク先メッセージの要約`」
でもいいかなと思ってます

**Comment by book000** [comment]
全省略だとなんのURLかわからんように思えてなあ…。URL先のタイトル拾うとかでもいいかもねえ

**Comment by book000** [comment]
私達みたいにサブモニタにDiscordおける人はいいけど、シングルモニタで音しか聞いてない人がどうかしら

**Comment by poker99981** [comment]
#9のような場合だと [こういうの](https://discord.com/channels/597378876556967936/623153228267388958/831153444454531082) とかみたいなファイルを読み上げたときに大変になると思います...

**Comment by yuuahp** [comment]
リンク先タイトルを最大15~20文字くらい読み上げる...
でどうですか

Discordリンクの場合は
「メッセージリンク-リンク先メッセージの要約」
で解決できると思います

**Comment by X8Z-p0keR** [comment]
そうですね
ファイル名の読み上げだとtwitterとかgyazoの画像をそのまま上げた場合、数十文字ぐらいの数字英字混合のファイル名になったりするので読み上げる文字数を定めるのがいいと思います

**Comment by book000** [comment]
👍

**Comment by book000** [comment]
#9 はクローズします
