### ISSUE TITLE
ユーザーのVCへのjoin/leave後の読み上げの順番がおかしい

### ISSUE THREAD

**Issue by X8Z-p0keR** [jaoafa/JDA-VCSpeaker#26]
誰かがVCチャンネルにjoin/leaveすると
・#VCに新たに書き込まれるまで読み上げが一旦止まる
・#VCに新たに書き込まれると「最新の書き込み」を読み上げる
・その後join/leaveメッセージを読んでいる間の書き込みを読み上げ始める
という挙動になっていて、読み上げの順番がおかしくなっている

**Comment by kohonayoshi** [comment]
なお、この状況は文章の長さによって挙動が変わり
①長めの文章の場合(例：誰かがVCにjoin/leaveした場合)
・#VCに新たに書き込まれるまで読み上げが一旦止まる
・#VCに新たに書き込まれると「最新のチャット」を読み上げる
・その後一番古い✅の付いたチャットを読み上げるが、以降は再度#VCに何かを書き込まないと読み上げが再開しない
②短めの文章の場合(例：a)
・#VCに新たに書き込まれるまで読み上げが一旦止まる
・#VCに新たに書き込まれると「最新のチャット」を読み上げる
・その後古い順に✅の付いたチャットを読み上げ始め、✅の付いた文章のうち「長めの文章」のチャットが回ってくるまでは✅の付いたチャットを読み上げ続ける

**Comment by book000** [comment]
デバッグコードを色々噛まして原因調査しました。纏めます。

## 原因

読み上げ中であることを示すリアクションを付けるためにチャンネルとメッセージのIDを保持しているが、参加・退出の際はこれらID情報がなく結果として `TrackScheduler.onTrackEnd` において `getUserData()` は NULL を返すため、`getTextChannelById` でのメッセージ取得処理においてエラー(おまけにこのエラーはコンソールに表示されない)が発生しそのあとに続く `nextTrack()` が呼び出されない。

## 解決方法

いくつかの解決方法があると思われます。適度に取捨選択してください

1. `TrackScheduler.queue` でキュー管理するクラスを `AudioTrack` ではなく、独自クラスをキュー管理して、その独自クラスで `AudioTrack` と `ChannelId` と `MessageId` ( `Message` クラス自体を保持してもいいと思う) を持たせる。getUserDataは使わない？
2. `getUserData()` の返り値を確認し、`null` ならメッセージリアクション処理を行わない
3. 参加・退出時のチャンネル・メッセージIDをVCWatcherが送信する参加・退出メッセージIDで割り当て、そのメッセージにリアクションがつくようにする

## その他お節介

- 不要な `import` が残っていたり `&&` のスペースなしとか使われていないクラスとかが残っていて、下手に触って自動でフォーマッター掛かると無駄にレビューファイル数増えるかと思ったのでこちらで直してしてプルリク送るのはやめておきました
- `.gitignore` に `.idea` と `*.imi` を追加したほうが他の人が開発しやすいかもしれません ( `IntelliJ IDEA gitignore` とかで検索)
- チャンネル・メッセージ取得とかでnullチェックがされていないのが非常に気になっていますが…まあ
