### ISSUE TITLE
各パラメータのユーザー当たりデフォルト値

### ISSUE THREAD

**Issue by book000** [jaoafa/JDA-VCSpeaker#29]
`speaker`, `speed`, `emotion` などのパラメータをユーザー毎にデフォルト値設定できるようにしてほしいかも。
音声のみでユーザーを聞き分けている場合に分かりにくいって人がいないこともないので。

- `;default user speaker bear`: パラメータを指定しないときの実行者ユーザーの `speaker` のデフォルト値を `bear` にする
- `;default user speed 200`: パラメータを指定しないときの実行者ユーザーの `speed` のデフォルト値を `200` にする
- `;default global speaker bear`: パラメータを指定しないときの全員の `speaker` のデフォルト値を `bear` にする

**Comment by yuuahp** [comment]
configに保存ですか

**Comment by book000** [comment]
configよりかはべつのjsonファイルじゃないかなあ

**Comment by yuuahp** [comment]
了解です
