### ISSUE TITLE
次にトラックがない場合、リアクションが消えない

### ISSUE THREAD

**Issue by book000** [jaoafa/JDA-VCSpeaker#34]
https://github.com/jaoafa/JDA-VCSpeaker/blob/81dc14fae1a902243c84fc04880c7d8ad34c9194/src/main/java/com/jaoafa/jdavcspeaker/Player/TrackScheduler.java#L55

69行目のリアクション削除処理をifの外側に出す必要がある。

**Comment by yuuahp** [comment]
なおしました
