### ISSUE TITLE
VCの名前を変更できる title コマンドの実装

### ISSUE THREAD

**Issue by book000** [jaoafa/JDA-VCSpeaker#44]
`;title test`: 参加しているVCの名前を「`test`」に変更する。

そのVCから人が全員退出したら、元のVC名に戻す。
デフォルトVC名をコマンドで変更できるようにしてもいいと思う(adminstratorsのみ)

**Comment by yuuahp** [comment]
やります🤚

**Comment by yuuahp** [comment]
jao鯖に限定した機能ですか？
それともどの鯖でも使えるようにしますか？

**Comment by book000** [comment]
どの鯖でも。

デフォルトVC名は定義ファイルを最初から用意するよりもadminstrators限定でコマンドを使って設定できた方が使いやすいかも(e.g. `;defaultvcname 768452603402649640 🧀CheeseFactory(WorkingSpace)` ・ allで現行のVC名をデフォルトとして全保存: `;defaultvcname all`)

**Comment by book000** [comment]
デフォルトVC名の設定がなされていない場合、とりあえず `;title` で設定される前のVC名をデフォルトVC名として保持してしまうのがユーザ目線的には使いやすいかも

**Comment by book000** [comment]
まとめると

## コマンド

コマンド名に関しては変更してよい。特に `defaultvcname` は長すぎるかもしれない

- `;title <Title>`: 参加しているVCの名前を変更する。
- `;defaultvcname <Channel ID> <Name>`: チャンネルIDとデフォルトVC名を紐付ける。Adminstratorsの権限ロールを持つ人のみが使用可能
- `;defaultvcname all`: そのサーバの全てのチャンネルIDとデフォルトVC名を紐付ける。Adminstratorsの権限ロールを持つ人のみが使用可能
- その他: `defaultvcname` にリスト表示引数とか加えてもいいかも

## 機能

- `;title` で設定されたVCチャンネルからすべてのユーザーが退出した場合、そのチャンネル名は `;defaultvcname` または後述する処理で定義されたチャンネル名に戻す
- `;title` 実行時、デフォルトチャンネル名が設定されていない場合は実行時のVCチャンネル名をデフォルトとして設定する

## その他

- チャンネル名を戻す処理を行うかどうかに関しては、VCSpeakerが再起動するなどのケースも考えてなるべく実施可否をメモリ上に持たすのではなく定義とのイコール比較をおこなって変えるような実装にしたほうがいいかも

**Comment by yuuahp** [comment]
了解です👍

**Comment by yuuahp** [comment]
仕様が大体確定しました
## コマンド
- `;title name`
vc名を一時的に変更。全員退出時にリセットします。
もしデータが登録されていなかった場合は、最初の実行とみなし、すべてのVC名をデフォルトとして同期します。
- `;vcname sync/syncall`
現在のvc名が一時的かどうかに関わらず、強制的に上書き同期します。

## イベント
- `Event_Disconnect`
誰もいなくなった場合にリセットします。
- `Event_SyncVCName`
VCチャンネル名が変更された際に動作。
VCSpeakerの変更でない場合は、手動での変更とみなし、
そのちゃねんるの新しい名前をデフォルトとして設定します。

だいぶ変わっちゃいましたがこれでも大丈夫ですか？

**Comment by book000** [comment]
「同期」の定義が若干よくわからん…、`DiscordのVC名 → デフォルトVC名定義ファイル` なのか `デフォルトVC名定義ファイル → DiscordのVC名` なのか
前者なら `save` とかだし、後者なら `reset`, `load` とかそこらな気がするし

同期 `sync` の定義って「二者の変更を両方受け入れ、マージして二者の結果を同じとする` じゃないかなあと思ってるのだけど

**Comment by book000** [comment]
あと、`title` の

> もしデータが登録されていなかった場合は、最初の実行とみなし、すべてのVC名をデフォルトとして同期します。

についてだけど、(ここでの `同期` は `保存` であるとみなして)これは `既に保存されたことがあるが、新規チャンネルの作成・そのチャンネルでの title の実行によって全部が上書きされてしまう` ケースというのは想定してる？
正直わざわざ全部保存せずともそのチャンネルだけのチャンネル名だけでもいいのかな？と思ってたんだけどなぜ全チャンネルの情報持たせるのか知りたい

**Comment by yuuahp** [comment]
title実行時は当該チャンネルだけを保存するようにしました。
ユーザーが一括上書き保存を実行した場合にもmodifiedがtrueの場合はスキップするようにしました。
あとsaveに直しました。

**Comment by book000** [comment]
ぬ。とりあえずそれで実装お願いします
プルリクか何かにしてもらえるとこっちで見られるのでいいかも

**Comment by yuuahp** [comment]
プルリク送ります
