### ISSUE TITLE
強調したい文字のspeedを半分にする

### ISSUE THREAD

**Issue by kohonayoshi** [jaoafa/JDA-VCSpeaker#55]
強調されたチャットが見つかった場合、そのチャットの文章を再構成し、speedを設定値の半分にして読み上げる

【例】
※発言者の;defaultは speed:120とする
`**こ　れ　は　ひ　ど　い**` が発見された場合、 `これはひどい speed:60` に置き換える

【強調の例】
```
**これはひどい**
**こ れ は ひ ど い**
こ　れ　は　ひ　ど　い
```

【備考】
発言者の;defaultのspeedを割った数値が50を下回る場合、speed:50 で固定する
判定は「全ての文字の間に全角スペース・半角スペースがあるか」とか…

**Comment by yuuahp** [comment]
`.[ 　]+.`
(めも)

**Comment by book000** [comment]
`こ　れ　は　ひ　ど　い` → `^(.[　 ]){2,}.$`
アスタリスク囲いを許容するなら `^\*\*(.[　 ]){2,}.\*\*$`

ただユーザが入力するものだしかなりばらけるだろうと思うからどこまで細かく考えるかはうーんだと思う
