### ISSUE TITLE
VCwatcherによってボイスチャンネル名が変更されたときに、変更された旨を読み上げてほしい

### ISSUE THREAD

**Issue by X8Z-p0keR** [jaoafa/JDA-VCSpeaker#56]

**Comment by X8Z-p0keR** [comment]
マウス操作を誤りました
すべての記憶を抹消してください

**Comment by book000** [comment]
https://github.com/jaoafa/JDA-VCSpeaker/commit/466c30d892ddcfe86fffc31d7c4ee763500d9c53
